-- INSERT INTO SEAT (ID, SENSOR_ID, LOCATION) VALUES ("1", "1", "l1");
-- INSERT INTO SEAT (ID, SENSOR_ID, LOCATION) VALUES ("2", "3", "l2");
SELECT * FROM "SEAT";
SELECT * FROM "SENSOR";
SELECT "SENSOR".ID, "SEAT".LOCATION, "SENSOR".STATUS, "SENSOR".TEMP, "SENSOR".BATTERY, "SEAT".ID FROM "SEAT" INNER JOIN "SENSOR" ON "SENSOR".ID = "SEAT".SENSOR_ID